<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>FragmentsUnity.Core</AssemblyName>
    <RootNamespace>FragmentsUnity</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <PackageRoot>$(MSBuildThisFileDirectory)..\..\..</PackageRoot>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="$(PackageRoot)\Runtime\AssemblyInfo.cs" />
    <Compile Include="$(PackageRoot)\Runtime\Core\**\*.cs" />
    <Compile Include="$(PackageRoot)\Runtime\Generated\**\*.cs" />
    <Compile Include="$(PackageRoot)\Runtime\ThirdParty\**\*.cs" />
  </ItemGroup>
</Project>
